import PDFDocument from 'pdfkit'

const DARK = '#0a1628'
const ORANGE = '#f97316'
const GRAY = '#475569'
const LIGHT_GRAY = '#94a3b8'
const WHITE = '#ffffff'
const BODY = '#1e293b'

function header(doc: InstanceType<typeof PDFDocument>, title: string, businessName: string, date: string) {
  // Top bar
  doc.rect(0, 0, doc.page.width, 70).fill(DARK)
  doc.fillColor(ORANGE).fontSize(20).font('Helvetica-Bold').text('Noveliotech CRM', 40, 18)
  doc.fillColor(WHITE).fontSize(9).font('Helvetica').text('Digital Agency SEO Report', 40, 44)
  doc.fillColor(LIGHT_GRAY).fontSize(9).text(date, doc.page.width - 150, 30, { width: 110, align: 'right' })

  // Report title block
  doc.rect(0, 70, doc.page.width, 55).fill('#0d1f3c')
  doc.fillColor(WHITE).fontSize(15).font('Helvetica-Bold').text(title, 40, 84)
  doc.fillColor(ORANGE).fontSize(10).font('Helvetica').text(businessName, 40, 105)

  doc.y = 145
}

function sectionHeading(doc: InstanceType<typeof PDFDocument>, text: string) {
  if (doc.y > doc.page.height - 120) doc.addPage()
  doc.moveDown(0.6)
  doc.rect(40, doc.y, doc.page.width - 80, 24).fill(DARK)
  doc.fillColor(ORANGE).fontSize(11).font('Helvetica-Bold')
    .text(text.toUpperCase(), 50, doc.y - 18, { width: doc.page.width - 100 })
  doc.moveDown(0.8)
  doc.fillColor(BODY).fontSize(10).font('Helvetica')
}

function subHeading(doc: InstanceType<typeof PDFDocument>, text: string) {
  doc.moveDown(0.4)
  doc.fillColor(DARK).fontSize(10).font('Helvetica-Bold').text(text)
  doc.moveDown(0.2)
  doc.fillColor(BODY).fontSize(10).font('Helvetica')
}

function scoreBadge(doc: InstanceType<typeof PDFDocument>, score: number) {
  const x = doc.page.width - 130
  const color = score >= 70 ? '#16a34a' : score >= 50 ? ORANGE : '#dc2626'
  doc.roundedRect(x, 148, 90, 60, 8).fill(color)
  doc.fillColor(WHITE).fontSize(32).font('Helvetica-Bold').text(String(score), x, 158, { width: 90, align: 'center' })
  doc.fontSize(9).font('Helvetica').text('/ 100', x, 192, { width: 90, align: 'center' })
}

function parseAndRender(doc: InstanceType<typeof PDFDocument>, content: string) {
  const lines = content.split('\n')
  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line) { doc.moveDown(0.3); continue }

    if (line.startsWith('## ')) {
      sectionHeading(doc, line.slice(3))
    } else if (line.startsWith('### ')) {
      subHeading(doc, line.slice(4))
    } else if (line.match(/^\d+\.\s/)) {
      // Numbered list
      if (doc.y > doc.page.height - 60) doc.addPage()
      const num = line.match(/^(\d+)\.\s(.*)/)!
      doc.fillColor(ORANGE).fontSize(10).font('Helvetica-Bold')
        .text(num[1] + '.', 40, doc.y, { width: 20, continued: true })
      doc.fillColor(BODY).font('Helvetica')
        .text(' ' + num[2], { width: doc.page.width - 110 })
    } else if (line.startsWith('- ') || line.startsWith('• ')) {
      if (doc.y > doc.page.height - 60) doc.addPage()
      doc.fillColor(ORANGE).text('•', 40, doc.y, { width: 15, continued: true })
      doc.fillColor(BODY).fontSize(10).font('Helvetica')
        .text(' ' + line.slice(2), { width: doc.page.width - 110 })
    } else if (line.startsWith('**') && line.endsWith('**')) {
      doc.fillColor(DARK).fontSize(10).font('Helvetica-Bold').text(line.slice(2, -2))
    } else {
      if (doc.y > doc.page.height - 60) doc.addPage()
      doc.fillColor(BODY).fontSize(10).font('Helvetica').text(line, { width: doc.page.width - 80 })
    }
  }
}

export async function buildSummaryPDF(
  businessName: string,
  city: string,
  score: number,
  content: string,
  date: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' })
    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    header(doc, 'SEO Audit — Executive Summary', `${businessName} · ${city}`, date)
    scoreBadge(doc, score)
    parseAndRender(doc, content)

    // Footer
    doc.fontSize(8).fillColor(LIGHT_GRAY)
      .text('Generated by Noveliotech CRM · Confidential', 40, doc.page.height - 30, {
        width: doc.page.width - 80, align: 'center',
      })
    doc.end()
  })
}

export async function buildDetailedPDF(
  businessName: string,
  city: string,
  score: number,
  content: string,
  date: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4', autoFirstPage: true })
    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    header(doc, 'SEO Audit — Full Report', `${businessName} · ${city}`, date)
    scoreBadge(doc, score)
    parseAndRender(doc, content)

    // Page numbers
    const range = doc.bufferedPageRange()
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i)
      doc.fontSize(8).fillColor(LIGHT_GRAY)
        .text(`Page ${i + 1} of ${range.count}  ·  Noveliotech CRM  ·  Confidential`,
          40, doc.page.height - 30, { width: doc.page.width - 80, align: 'center' })
    }
    doc.end()
  })
}
